SimpleBlog/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('blog.urls')),
]

blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Flynn on 2018-02-25 15:09
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.get_blogs, name='index'),
	url(r'^detail/(?P<pk>\d+)$', views.get_detail, name='detail'),
]

blog/models/blog.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Flynn on 2018-02-25 14:28
from django.db import models
from .category import Category
from .tag import Tag


class Blog(models.Model):
	"""
	博客
	"""
	title = models.CharField('标题', max_length=32)
	author = models.CharField('作者', max_length=16)
	content = models.TextField('正文')
	created = models.DateTimeField('发布时间', auto_now_add=True)

	category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
	tags = models.ForeignKey(Tag, verbose_name='标签', on_delete=models.CASCADE)

blog/models/category.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Flynn on 2018-02-25 14:27
from django.db import models


class Category(models.Model):
	"""
	分类
	"""
	name = models.CharField('名称', max_length=16)

blog/models/comment.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Flynn on 2018-02-25 14:31
from django.db import models
from .blog import Blog


class Comment(models.Model):
	"""
	评论
	"""
	blog = models.ForeignKey(Blog, verbose_name='博客', on_delete=models.CASCADE)

	# 用户信息
	name = models.CharField('称呼', max_length=16)
	email = models.EmailField('邮箱')
	content = models.CharField('内容', max_length=140)
	# 评论时间
	created = models.DateTimeField('发表时间', auto_now_add=True)

blog/models/tag.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Flynn on 2018-02-25 14:27
from django.db import models


class Tag(models.Model):
	"""
	标签
	"""
	name = models.CharField('名称', max_length=16)

blog/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Flynn on 2018-02-25 15:21
from django import forms


class CommentForm(forms.Form):
	"""
	评论表单
	"""
	name = forms.CharField(label='称呼', max_length=16, error_messages={
		'required': '请填写您的称呼',
		'max_length': '称呼太长',
	})

	email = forms.EmailField(label='邮箱', error_messages={
		'required': '请填写您的邮箱',
		'invalid': '邮箱格式不正确',
	})

	content = forms.CharField(label='评论内容', error_messages={
		'required': '请填写您的评论内容',
		'max_length': '评论内容太长',
	})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from .forms import CommentForm
from .models import Comment


def get_blogs(request):
	ctx = {
		'blogs': Blog.objects.all().order_by('-created')
	}
	return render(request, 'blog/blog-list.html', ctx)


def get_detail(request, pk):
	blog = get_object_or_404(Blog, pk=pk)

	if request.method == 'GET':
		form = CommentForm()
	else:
		form = CommentForm(request.POST)
		if form.is_valid():
			cleaned_data = form.cleaned_data
			cleaned_data['blog'] = blog
			Comment.objects.create(**cleaned_data)

	ctx = {
		'blog': blog,
		'comments': blog.comment_set.all().order_by('-created'),
		'form': form,
	}
	return render(request, 'blog/blog-detail.html', ctx)

blog/templates/blog/blog-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ blog.title }}</title>
    <style>
        .blog {
            padding: 20px 0px;
        }

        .blog .info span {
            padding-right: 10px;
        }

        .blog .summary {
            padding-top: 20px;
        }
    </style>
</head>
<body>
<div class="header">
    <span><a href="{% url 'blog:index' %}">博客</a> - <a
            href="{% url 'blog:detail' blog.pk %}">{{ blog.title }}</a></span>
</div>
<div class="content">
    <div class="blog">
        <div class="title">
            <span style="font-size: 30px;color:red;">{{ blog.title }}</span>
        </div>
        <div class="info">
            <span class="category" style="color: #ff9900">{{ blog.category.name }}</span>
            <span class="author" style="color: #4a86e8">{{ blog.author }}</span>
            <span class="created" style="color: #6aa84f">{{ blog.created|date:"Y-m-d H:i" }}</span>
        </div>
        <div class="summary">
            {{ blog.content }}
        </div>
    </div>
    <div class="comment">
        <div class="comments-display" style="padding-top:20px;">
            <h3>评论({{ comments|length }})：</h3>
            {% for comment in comments %}
                <div class="comment-field" style="padding-top:10px;">
                    <span style="color:rosybrown;font-size: 20px;">{{ comment.name }}</span>
                    <sub>{{ comment.created|date:"Y-m-d" }}</sub>
                    说: {{ comment.content }}
                </div>
                <hr/>
            {% endfor %}
        </div>
        <div class="comment-post" style="padding-top:20px;">
            <h3>提交评论：</h3>
            <form action="{% url 'blog:detail' blog.id %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="input-field" style="padding-top:10px;">
                        {{ field.label }}:{{ field }}
                    </div>
                    <div class="error" style="color:red;">
                        {{ field.errors }}
                    </div>
                {% endfor %}
                <button type="submit" style="margin-top:10px;">提交</button>
            </form>
        </div>
    </div>
</div>
</body>
</html>

blog/templates/blog/blog-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客首页</title>
    <style>
        .blog {
            padding: 20px 0px;
        }

        .blog .info span {
            padding-right: 10px;
        }

        .blog .summary {
            padding-top: 20px;
        }
    </style>
</head>
<body>
<div class="header">
    <h1>博客首页</h1>
</div>
{% for blog in blogs %}
    <div class="blog">
        <div class="title">
            <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
        </div>
        <div class="info">
            <span class="category" style="color: #ff9900">{{ blog.category.name }}</span>
            <span class="author" style="color: #4a86e8">{{ blog.author }}</span>
            <span class="created" style="color: #6aa84f">{{ blog.created|date:"Y-m-d H:i" }}</span>
        </div>
        <div class="summary">
            {{ blog.content|truncatechars:100 }}
        </div>
    </div>
{% endfor %}
</body>
</html>